### ISSUE TITLE
Trigger title change on event

### ISSUE THREAD

**Issue by juzsal** [nonplus/angular-ui-router-title#5]
Hi,

I'm wondering how I might be able to trigger a change in the title when an event occurs? I.e. something like:

```
$rootScope.$on('event:languageChanged', function () {
    // somehow use $title here
});
```

**edit**: I'm using [angular-translate](http://www.github.com/angular-translate/angular-translate). I tried the following, but it didn't work:

```
<title ng-bind-template="{{$title | translate}}"></title>
```

P.S. Great plugin, thanks!

**Comment by lunks** [comment]
I believe just updating `$rootScope.$title` might work, but I haven't tried it yet.

**Comment by xeroxoid** [comment]
For me that only worked if I defered the execution (via lodash/underscore _.defer function) i.e.:

``` javascript
    _.defer(function () {
        $rootScope.$title = 'Photo of ' + user.name;
    });
```

else something overwrote it to blank...
